kind: Service
apiVersion: v1
metadata:
  labels:
    app: gs-webui
    version: 12.0.1
  name: gs-webui
spec:
  ports:
    - port: 8099
      targetPort: 8099
      protocol: TCP
  selector:
    app: gs-webui
    version: 12.0.1
  type: LoadBalancer