kind: Service
apiVersion: v1
metadata:
  labels:
    app: xap-mgt-node
    version: 12.0.1
  name: xap-mgt-node
spec:
  ports:
    - port: 4174
      targetPort: 4174
      protocol: TCP
  selector:
    app: xap-mgt-node
    version: 12.0.1
  type: ClusterIP